exports.up = knex => knex.schema.createTable('tickets', table => {
  table.uuid('id').primary()
  table.string('title', 255)
    .unique()
    .notNullable()
  table.timestamp('created_at')
    .defaultTo(knex.fn.now())
    .notNullable()
  table.timestamp('updated_at')
  table.uuid('author')
    .references('users.id')
    .onDelete('CASCADE')
    .notNullable()
  table.uuid('ticket_user_admin')
    .references('users.id')
    .onDelete('CASCADE')
    .notNullable()
  table.enum('status', ['PENDENTE', 'PROGRESSO', 'CONCLUÍDO'])
    .defaultTo('PENDENTE')
    .notNullable()
  table.uuid('local_id')
    .references('locals.id')
    .onDelete('CASCADE')
    .notNullable()
  table.string('local_name', 255)
    .unique()
    .notNullable()
  table.text('address',)
    .unique()
    .notNullable()
  table.integer('local_company')
    .references('companies.id')
    .onDelete('CASCADE')
    .notNullable()
  table.integer('local_admin')
    .references('accountables.id')
    .onDelete('CASCADE')
    .notNullable()
})

exports.down = knex => knex.schema.dropTable('local_accountable')